version: '3.9'

services:
  postgres:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:create db:migrate db:seed && bin/rails server -b 0.0.0.0 -p 3001"
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development
    depends_on:
      - postgres

  client:
    build:
      context: ./client
    command: npm run dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  pg_data:
